<div class="main-content"> 
    <div class="page-content">
        <div class="page-header">
            <h1>
                Consulta de Tesis

            </h1>
        </div><!-- /.page-header -->
        <div class="row-fluid">
            <div class="col-xs-12">
                <form method="post" role="form" class="form-horizontal" action="<?php echo $this->url('consultas',array('action' => 'buscar')) ?>" >
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Búsqueda por titulo:</label>
                        <div class="col-sm-9">
                            <input class="col-xs-12 col-sm-12" type="text" name="titulo" id="form-field-1" placeholder="Escriba la tesis a buscar" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label no-padding-right" for="form-field-select-2">Especialidad:</label>
                        <div class="col-sm-9">
                            <select class="chzn-select col-sm-5" id="form-field-select-2" name="especialidad" data-placeholder="Seleccione la especialidad" >
                                <option value="" /> Todas las especialidades
                                <?php
                                    foreach($lista as $resul) :
                                        echo '<option value="'.$resul["ID"].'" />'.$resul["NOMBRE"];
                                    endforeach;
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-actions center">
                        <input type="submit" class="btn btn-lg btn-success" value="Iniciar"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('[data-rel=tooltip]').tooltip();
    $('[data-rel=popover]').popover({html:true});
</script>