<?php
$this->headTitle("Registro y Consulta de Tesis -- UNEFA [TUTORES]");

?>
<div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>
                <ul class="breadcrumb">
                        <li>
                                <i class="icon-home home-icon"></i>
                                <a href="<?php echo $this->url('home') ?>">Home</a>
                        </li>

                        <li>
                                <a href="<?php echo $this->url('tutores') ?>">Tutores</a>
                        </li>
                        <li class="active">Agregar</li>
                </ul><!--.breadcrumb-->

                <div class="nav-search" id="nav-search">
                </div><!--#nav-search-->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    Ingreso de Tutores
                    <small>
                        <i class="icon-double-angle-right"></i>
                        En este modulo podemos agregar un Tutor a la Base de Datos
                    </small>
                </h1>
            </div><!-- /.page-header -->
                <div class="row-fluid">
                    <div class="col-xs-12">
                        <?php
                                if ($msg != ""){
                                        echo '<div class="alert alert-'.$satis.'">',$msg.'</div>';
                                }
                        ?>
                        <!--PAGE CONTENT BEGINS-->
                        <h3 class="header smaller lighter red">
                                Datos Básicos
                        </h3>
                        <br>
                        <form method="post" role="form" class="form-horizontal" action="<?php echo $this->url('tutores',array('action' => 'add')) ?>" >
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Cedula:</label>
                                <div class="col-sm-9">
                                    <input class="col-xs-12 col-sm-6" type="text" name="cedula" id="form-field-2" placeholder="Cedula del tutor" required />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Nombre del Tutor:</label>
                                <div class="col-sm-9">
                                    <input class="col-xs-12 col-sm-6" type="text" name="nombre" id="form-field-1" placeholder="Nombre del tutor" required />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right" for="form-field-select-1">Tipo de Tutor:</label>
                                <div class="col-sm-9">
                                    <select class="chzn-select col-sm-3" id="form-field-select-1" name="tipo">
                                        <option value="1" />Metodológico
                                        <option value="2" />Académico
                                    </select>
                                </div>
                            </div>
                            <div class="form-actions center">
                                <input type="submit" class="btn btn-success" value="Guardar"/>
                                <a href="<?php echo $this->url('tutores') ?>" class="btn btn-small btn-warning">
                                        Cancelar
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
        </div><!--/.page-content-->


</div><!--/.main-content-->
        <script src="/css/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="/css/assets/js/jquery.ui.touch-punch.min.js"></script>
        <script src="/css/assets/js/chosen.jquery.min.js"></script>
        <script src="/css/assets/js/fuelux/fuelux.spinner.min.js"></script>
        <script src="/css/assets/js/date-time/daterangepicker.min.js"></script>
        <script src="/css/assets/js/date-time/moment.min.js"></script>
        <script src="/css/assets/js/date-time/bootstrap-timepicker.min.js"></script>
        <script src="/css/assets/js/date-time/bootstrap-datepicker.min.js"></script>
        <script src="/css/assets/js/bootstrap-colorpicker.min.js"></script>
        <script src="/css/assets/js/jquery.knob.min.js"></script>
        <script src="/css/assets/js/jquery.autosize-min.js"></script>
        <script src="/css/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
        <script src="/css/assets/js/jquery.maskedinput.min.js"></script>
        <script src="/css/assets/js/bootstrap-tag.min.js"></script>
<script>
    $(<?php echo '"#'.$this->activo.'"'; ?>).addClass("active");
    $(".chzn-select").chosen(); 
    $("#form-field-2").keydown(function(event) {
        if(event.shiftKey){
             event.preventDefault();
        }
        if (event.keyCode == 46 || event.keyCode == 8)    {
        }
        else {
            if (event.keyCode < 95) {
                if (event.keyCode < 48 || event.keyCode > 57) {
                     event.preventDefault();
                }
            }
             else {
                if (event.keyCode < 96 || event.keyCode > 105) {
                    event.preventDefault();
                }
             }
        }
    });
</script>
