<?php
$this->headTitle("Registro y Consulta de Tesis -- UNEFA [TUTORES]");

foreach($lista as $resul) :
    $id             = $resul["ID"];
    $titulo         = $resul["TITULO"];
    $ano            = $resul["ANO"];
    $autores        = $resul["AUTORES"];
    $especialidad   = $resul["ESPECIALIDAD"];
    $tutor_t        = $resul["TUTOR_T"];
    $tutor_m        = $resul["TUTOR_M"];
    $resumen        = $resul["RESUMEN"];
    $t_d            = $resul["T_D"];
    $comp_1         = $resul["COMP_1"];
    $intro_1        = $resul["INTRO_1"];
    $cap1_1         = $resul["CAP1_1"];
    $cap2_1         = $resul["CAP2_1"];
    $cap3_1         = $resul["CAP3_1"];
    $cap4_1         = $resul["CAP4_1"];
    $conc_1         = $resul["CONC_1"];
    $comp           = $resul["COMP"];
    $intro          = $resul["INTRO"];
    $cap1           = $resul["CAP1"];
    $cap2           = $resul["CAP2"];
    $cap3           = $resul["CAP3"];
    $cap4           = $resul["CAP4"];
    $conc           = $resul["CONC"];
endforeach;
$checa = "";
if($t_d != "2"){
    $checa = "checked='checked'";
}
?>

<div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                    try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>
                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home home-icon"></i>
                        <a href="<?php echo $this->url('home') ?>">Home</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('tesis') ?>">Tesis</a>
                    </li>
                    <li class="active">Agregar</li>
                </ul><!--.breadcrumb-->

                <div class="nav-search" id="nav-search">
                </div><!--#nav-search-->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    Edición de Tesis
                    <small>
                        <i class="icon-double-angle-right"></i>
                        Este modulo editara la tesis seleccionada!
                    </small>
                </h1>
            </div><!-- /.page-header -->
                <div class="row-fluid">
                    <div class="col-xs-12">
                        <?php
                                if ($msg != ""){
                                        echo '<div class="alert alert-'.$satis.'">',$msg.'</div>';
                                }
                        ?>
                        <!--PAGE CONTENT BEGINS-->

                        <h3 class="header smaller lighter red">
                                Datos Básicos
                        </h3>
                                    <br>
                                    <form method="post" role="form" class="form-horizontal" action="<?php echo $this->url('tesis',array('action' => 'edit','id' => $id)) ?>" enctype="multipart/form-data" >
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Titulo:</label>
                                            <div class="col-sm-9">
                                                <input value="<?php echo $titulo; ?>" class="col-xs-12 col-sm-12" type="text" name="titulo" id="form-field-1" placeholder="Titulo de la Tesis" required />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-2">Autores:</label>
                                            <div class="col-sm-9">
                                                <input value="<?php echo $autores; ?>" class="col-xs-10 col-sm-5" type="text" name="autores" id="form-field-2" placeholder="Autores" required />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-select-1">Año de Publicación:</label>
                                            <div class="col-sm-9">
                                                <select class="chzn-select col-sm-3" id="form-field-select-1" name="ano" data-placeholder="Año de publicacion" required>
                                                    <option value="" />
                                                    <option value="2005" />2005
                                                    <option value="2006" />2006
                                                    <option value="2007" />2007
                                                    <option value="2008" />2008
                                                    <option value="2009" />2009
                                                    <option value="2010" />2010
                                                    <option value="2011" />2011
                                                    <option value="2012" />2012
                                                    <option value="2013" />2013
                                                    <option value="2014" />2014
                                                    <option value="2015" />2015
                                                </select>
                                                <?php echo "<script> $(\"#form-field-select-1 option[value='".$ano."']\").attr(\"selected\",true);</script>"; ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-select-2">Especialidad:</label>
                                            <div class="col-sm-9">
                                                <select class="chzn-select col-sm-5" id="form-field-select-2" name="especialidad" data-placeholder="Seleccione la especialidad" required>
                                                    <option value="" />
                                                    <?php
                                                        foreach($lista1 as $resul) :
                                                            echo '<option value="'.$resul["ID"].'" />'.$resul["NOMBRE"];
                                                        endforeach;
                                                    ?>
                                                </select>
                                                <?php echo "<script> $(\"#form-field-select-2 option[value='".$especialidad."']\").attr(\"selected\",true);</script>"; ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-select-3">Tutor Teórico:</label>
                                            <div class="col-sm-9">
                                                <select class="chzn-select col-sm-5" id="form-field-select-3" name="tutor_t" data-placeholder="Tutor Teórico" required>
                                                    <option value="" />
                                                    <?php
                                                        foreach($lista2 as $resul) :
                                                            echo '<option value="'.$resul["ID"].'" />'.$resul["NOMBRES"];
                                                        endforeach;
                                                    ?>
                                                </select>
                                                <?php echo "<script> $(\"#form-field-select-3 option[value='".$tutor_t."']\").attr(\"selected\",true);</script>"; ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-select-4">Tutor Metodológico:</label>
                                            <div class="col-sm-9">
                                                <select class="chzn-select col-sm-5" id="form-field-select-4" name="tutor_m" data-placeholder="Tutor Metodológico" required>
                                                    <option value="" />
                                                    <?php
                                                        foreach($lista3 as $resul) :
                                                            echo '<option value="'.$resul["ID"].'" />'.$resul["NOMBRES"];
                                                        endforeach;
                                                    ?>
                                                </select>
                                                <?php echo "<script> $(\"#form-field-select-4 option[value='".$tutor_m."']\").attr(\"selected\",true);</script>"; ?>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="form-field-3">Resumen:</label>
                                            <div class="col-sm-9">
                                                <textarea class="autosize-transition form-control" name="resumen" id="form-field-3" placeholder="Resumen de la tesis" required><?php echo $resumen; ?></textarea>
                                            </div>
                                        </div>
                                        <h3 class="header smaller lighter orange">
                                                Datos Lógicos
                                        </h3>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label no-padding-right" for="switch-field-1">Documento Único:</label>
                                            <div class="col-sm-9">
                                                <label>
                                                    <input name="switch-field-1" id="switch-field-1" class="ace ace-switch ace-switch-5" type="checkbox" <?php echo $checa; ?>/>
                                                    <span class="lbl"></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="row-fluid">
                                                <div class="col-xs-12 col-sm-1"></div>
                                                <div class="col-xs-12 col-sm-5">
                                                    <div class="widget-box" id="coll1">
                                                        <div class="widget-header">
                                                            <h4>Documento a Texto Completo</h4>
                                                            <span class="widget-toolbar">
                                                                <a href="#" data-action="collapse">
                                                                    <i class="icon-chevron-up"></i>
                                                                </a>
                                                            </span>
                                                        </div>
                                                        <div class="widget-body">
                                                            <div class="widget-main">
                                                                <input type="file" id="id-input-file-1" name="completo" />
                                                                <?php
                                                                    if($t_d == "1"){
                                                                ?>
                                                                <h4>Documentos Disponibles</h4>
                                                                <hr>
                                                                <a target="_balnk" href="<?php echo $comp_1; ?>">
                                                                    <span class="label label-success arrowed-in arrowed-in-right">
                                                                        Completo
                                                                    </span>
                                                                </a>
                                                                <?php
                                                                    }
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-5">
                                                    <div class="widget-box" id="coll2">
                                                        <div class="widget-header">
                                                            <h4>Tesis Dividida por Capitulos</h4>
                                                            <span class="widget-toolbar">
                                                                <a href="#" data-action="collapse">
                                                                    <i class="icon-chevron-up"></i>
                                                                </a>
                                                            </span>
                                                        </div>
                                                        <div class="widget-body">
                                                            <div class="widget-main">
                                                                <input type="file" id="id-input-file-2" name="intro" />
                                                                <input type="file" id="id-input-file-3" name="cap1" />
                                                                <input type="file" id="id-input-file-4" name="cap2" />
                                                                <input type="file" id="id-input-file-5" name="cap3" />
                                                                <input type="file" id="id-input-file-6" name="cap4" />
                                                                <input type="file" id="id-input-file-7" name="concl" />
                                                                <?php
                                                                    if($t_d == "2"){
                                                                ?>
                                                                <h4>Documentos Disponibles</h4>
                                                                <hr>
                                                                <?php
                                                                    if($intro == "1"){
                                                                        echo '<a target="_balnk" href="'.$intro_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Introduccion</spam>'
                                                                                . '</a> <br>';
                                                                        //echo '<a target="_balnk" href="/upload/tesis/1_INTRO_.PDF">Introduccion</a> <br>';
                                                                    }
                                                                    if($cap1 == "1"){
                                                                        echo '<a target="_balnk" href="'.$cap1_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Capitulo 1</spam>'
                                                                                . '</a> <br>';
                                                                    }
                                                                    if($cap2 == "1"){
                                                                        echo '<a target="_balnk" href="'.$cap2_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Capitulo 2</spam>'
                                                                                . '</a> <br>';
                                                                    }
                                                                    if($cap3 == "1"){
                                                                        echo '<a target="_balnk" href="'.$cap3_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Capitulo 3</spam>'
                                                                                . '</a> <br>';
                                                                    }
                                                                    if($cap4 == "1"){
                                                                        echo '<a target="_balnk" href="'.$cap4_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Capitulo 4</spam>'
                                                                                . '</a> <br>';
                                                                    }
                                                                    if($conc == "1"){
                                                                        echo '<a target="_balnk" href="'.$conc_1.'">'
                                                                                . '<span class="label label-success arrowed-in arrowed-in-right">Conclusion</spam>'
                                                                                . '</a> <br>';
                                                                    }
                                                                
                                                                    }
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-1"></div>
                                            </div>
                                        </div>
                                        <div class="form-actions center">
                                            <input type="submit" class="btn btn-success" value="Guardar"/>
                                            <a href="<?php echo $this->url('tesis') ?>" class="btn btn-small btn-warning">
                                                    Cancelar
                                            </a>
                                        </div>
                                    </form>
                                    
                                    
                                    
                                
                    </div>
                </div>
        </div><!--/.page-content-->


</div><!--/.main-content-->
        <script src="/css/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="/css/assets/js/jquery.ui.touch-punch.min.js"></script>
        <script src="/css/assets/js/chosen.jquery.min.js"></script>
        <script src="/css/assets/js/fuelux/fuelux.spinner.min.js"></script>
        <script src="/css/assets/js/date-time/daterangepicker.min.js"></script>
        <script src="/css/assets/js/date-time/moment.min.js"></script>
        <script src="/css/assets/js/date-time/bootstrap-timepicker.min.js"></script>
        <script src="/css/assets/js/date-time/bootstrap-datepicker.min.js"></script>
        <script src="/css/assets/js/bootstrap-colorpicker.min.js"></script>
        <script src="/css/assets/js/jquery.knob.min.js"></script>
        <script src="/css/assets/js/jquery.autosize-min.js"></script>
        <script src="/css/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
        <script src="/css/assets/js/jquery.maskedinput.min.js"></script>
        <script src="/css/assets/js/bootstrap-tag.min.js"></script>
<script>
    $(<?php echo '"#'.$this->activo.'"'; ?>).addClass("active");
</script>
<script>
    $(function() {
        $(".chzn-select").chosen(); 

        //we could just set the data-provide="tag" of the element inside HTML, but IE8 fails!
        var tag_input = $('#form-field-2');
        if(! ( /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase())) ) {
            tag_input.tag({
                placeholder:tag_input.attr('placeholder'),
                //enable typeahead by specifying the source array
                source: ace.variable_US_STATES,//defined in ace.js >> ace.enable_search_ahead
            });
        }
        else {
            //display a textarea for old IE, because it doesn't support this plugin or another one I tried!
            tag_input.after('<textarea id="'+tag_input.attr('id')+'" name="'+tag_input.attr('name')+'" rows="3">'+tag_input.val()+'</textarea>').remove();
            //$('#form-field-tags').autosize({append: "\n"});
        }


        //Autosize
        $('textarea[class*=autosize]').autosize({append: "\n"});
        $('textarea.limited').inputlimiter({
                remText: '%n character%s remaining...',
                limitText: 'max allowed : %n.'
        });


        //Input Files
        $('#id-input-file-1').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Seleccionar',
            btn_change:'Seleccionar',
            droppable:false,
            onchange:null,
            thumbnail:false //| true | large
            //whitelist:'gif|png|jpg|jpeg'
            //blacklist:'exe|php'
            //onchange:''
            //
        });

        $('#id-input-file-2').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Introducción',
            btn_change:'Introducción',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
        $('#id-input-file-3').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Capitulo 1',
            btn_change:'Capitulo 1',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
        $('#id-input-file-4').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Capitulo 2',
            btn_change:'Capitulo 2',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
        $('#id-input-file-5').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Capitulo 3',
            btn_change:'Capitulo 3',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
        $('#id-input-file-6').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Capitulo 4',
            btn_change:'Capitulo 4',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });
        $('#id-input-file-7').ace_file_input({
            no_file:'Seleccione un archivo PDF',
            btn_choose:'Conclusión',
            btn_change:'Conclusión',
            droppable:false,
            onchange:null,
            thumbnail:false,
            whitelist:'pdf'
            //blacklist:'exe|php'
            //onchange:''
            //
        });


    });
</script>
