<?php echo $this->doctype(); ?>

<html>
	<head>
	<meta charset="utf-8">
	<?php 
            echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false);
            echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
            //styles 
            echo $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.css');
            //Scripts 
            echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/bootstrap.js')
			->prependFile($this->basePath() . '/js/jquery.min.js')
	?>

		<noscript>
		 Para utilizar las funcionalidades completas de este sitio es necesario tener
		 JavaScript habilitado. Aquí están las <a href="http://www.enable-javascript.com/es/"
		 target="_blank"> instrucciones para habilitar JavaScript en tu navegador web</a>.
		</noscript>

		<!-- Estilo para banner Slide -->
		<style type="text/css">
                    .form-signin
                    {
                        max-width: 330px;
                        padding: 15px;
                        margin: 0 auto;
                    }
                    .form-signin .form-signin-heading, .form-signin .checkbox
                    {
                        margin-bottom: 10px;
                    }
                    .form-signin .checkbox
                    {
                        font-weight: normal;
                    }
                    .form-signin .form-control
                    {
                        position: relative;
                        font-size: 16px;
                        height: auto;
                        padding: 10px;
                        -webkit-box-sizing: border-box;
                        -moz-box-sizing: border-box;
                        box-sizing: border-box;
                    }
                    .form-signin .form-control:focus
                    {
                        z-index: 2;
                    }
                    .form-signin input[type="text"]
                    {
                        margin-bottom: -1px;
                        border-bottom-left-radius: 0;
                        border-bottom-right-radius: 0;
                    }
                    .form-signin input[type="password"]
                    {
                        margin-bottom: 10px;
                        border-top-left-radius: 0;
                        border-top-right-radius: 0;
                    }
                    .account-wall
                    {
                        margin-top: 40px;
                        padding: 40px 0px 20px 0px;
                        background-color: rgba(247,247,247,0.7);
                        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
                        
                    }
                    .login-title
                    {
                        color: #555;
                        font-size: 18px;
                        font-weight: 400;
                        display: block;
                    }
                    .profile-img
                    {
                        max-width: 120px;
                        max-height: 120px;
                        margin: 0 auto 10px;
                        display: block;
                    }
                    .need-help
                    {
                        margin-top: 10px;
                    }
                    .new-account
                    {
                        display: block;
                        margin-top: 10px;
                    }
                    .fullscreen_bg {
                        position: fixed;
                        top: 0;
                        right: 0;
                        bottom: 0;
                        left: 0;
                        background-size: cover;
                        background-position: 50% 50%;
                        background-image: url('<?php echo $this->basePath(). '../../img/index.jpg';?>');
                      }
		</style>
	</head>
	<body>
            <div id="fullscreen_bg" class="fullscreen_bg"> </div>
            <?php echo $this->content; ?>

        </body>
</html>