<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Tesis UNEFA</title>

        <meta name="description" content="Common form elements and layouts" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!--basic styles-->
        <!-- Le styles -->
        <style>
            @font-face {
              font-family: 'Open Sans';
              font-style: normal;
              font-weight: 300;
              src: local('Open Sans Light'), local('OpenSans-Light'), url(<?php echo $this->basePath().'/fonts/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff'; ?>) format('woff');
            }
            @font-face {
              font-family: 'Open Sans';
              font-style: normal;
              font-weight: 400;
              src: local('Open Sans'), local('OpenSans'), url(<?php echo $this->basePath().'/fonts/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff'; ?>) format('woff');
            }
        </style>
        <!-- basic styles -->

        <link href="/css/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="/css/assets/css/font-awesome.min.css" />

        <!--[if IE 7]>
          <link rel="stylesheet" href="/css/assets/css/font-awesome-ie7.min.css" />
        <![endif]-->

        <!-- page specific plugin styles -->

        <link rel="stylesheet" href="/css/assets/css/jquery-ui-1.10.3.custom.min.css" />
        <link rel="stylesheet" href="/css/assets/css/chosen.css" />
        <link rel="stylesheet" href="/css/assets/css/datepicker.css" />
        <link rel="stylesheet" href="/css/assets/css/bootstrap-timepicker.css" />
        <link rel="stylesheet" href="/css/assets/css/daterangepicker.css" />
        <link rel="stylesheet" href="/css/assets/css/colorpicker.css" />

        <!-- ace styles -->

        <link rel="stylesheet" href="/css/assets/css/ace.min.css" />
        <link rel="stylesheet" href="/css/assets/css/ace-rtl.min.css" />
        <link rel="stylesheet" href="/css/assets/css/ace-skins.min.css" />


        <!--[if lte IE 8]>
          <link rel="stylesheet" href="/css/assets/css/ace-ie.min.css" />
        <![endif]-->

        <!-- inline styles related to this page -->

        <!-- ace settings handler -->

        <script src="/css/assets/js/ace-extra.min.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

        <!--[if lt IE 9]>
        <script src="/css/assets/js/html5shiv.js"></script>
        <script src="/css/assets/js/respond.min.js"></script>
        <![endif]-->

<?php   
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='/css/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='/css/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="/css/assets/js/bootstrap.min.js"></script>
		<script src="/css/assets/js/typeahead-bs2.min.js"></script>

		<!-- page specific plugin scripts -->

		<!-- ace scripts -->

		<script src="/css/assets/js/ace-elements.min.js"></script>
		<script src="/css/assets/js/ace.min.js"></script>

        <style>
            .banner0
            {
                background-color: #0f8bea;
                background-image: url('<?php echo $this->basePath().'/img/tesis_banner2.png' ?>');
                background-repeat: no-repeat;
                height: 150px;
                background-position: right;
            }
        </style>
		



		<!--inline styles related to this page-->
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

        
        
	<body>
		<div class="navbar">
                    <div class="banner0">
                        <div class="navbar-inner banner0">
                            <div class="container-fluid">
                                <a href="<?php echo $this->url('home') ?>" class="navbar-brand">
                                    <small>
                                        <img src="<?php echo $this->basePath().'/img/img_1004581.png' ?>" style="max-height: 130px;"/>
                                            Sistema para Registro y Consulta de Tesis UNTES
                                    </small>
                                </a><!--/.brand-->
                            </div>
                        </div><!--/.container-fluid-->
                    </div><!--/.navbar-inner-->
		</div>

		<div class="main-container" id="main-container">
                    <script type="text/javascript">
                        try{ace.settings.check('main-container' , 'fixed')}catch(e){}
                    </script>
                    <div class="main-container-inner">
                        <a class="menu-toggler" id="menu-toggler" href="#">
                            <span class="menu-text"></span>
                        </a>
                        <div class="sidebar" id="sidebar">
                            <script type="text/javascript">
                                try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
                            </script>
                            <div class="sidebar-shortcuts" id="sidebar-shortcuts">
                                <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
                                    <button id="m_1" title="Ver manual del programador" class="btn btn-success tooltip-success" data-rel="tooltip" data-placement="top"><i class="icon-cogs"></i></button>
                                    <button id="m_2" title="Ver manual del analista" class="btn btn-info tooltip-info" data-rel="tooltip" data-placement="top"><i class="icon-user-md"></i></button>
                                    <button id="m_3" title="Ver manual de diseño" class="btn btn-warning tooltip-warning" data-rel="tooltip" data-placement="top"><i class="icon-coffee"></i></button>
                                    <button id="m_4" title="Ver manual del operador" class="btn btn-danger tooltip-error" data-rel="tooltip" data-placement="top"><i class="icon-cog"></i></button>
                                </div>
                                <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
                                    <span class="btn btn-success"></span>
                                    <span class="btn btn-info"></span>
                                    <span class="btn btn-warning"></span>
                                    <span class="btn btn-danger"></span>
                                </div>
                            </div><!--#sidebar-shortcuts-->

                            <ul class="nav nav-list">
                                <li id="home-1">
                                    <a href="<?php echo $this->url('home') ?>" >
                                        <i class="icon-home bigger-150"></i>
                                        <span class="menu-text"> INICIO </span>
                                    </a>
                                </li>
                                <li id="tesis-1">
                                    <a href="<?php echo $this->url('tesis') ?>">
                                        <i class="icon-book bigger-150"></i>
                                        <span class="menu-text"> TESIS </span>
                                    </a>
                                </li>
                                <li id="tutor-1">
                                    <a href="<?php echo $this->url('tutores') ?>">
                                        <i class="icon-group bigger-120"></i>
                                        <span class="menu-text"> TUTORES </span>
                                        </a>
                                </li>

                                <li id="especialidad-1">
                                    <a href="<?php echo $this->url('epecialidades') ?>">
                                        <i class="icon-list bigger-120"></i>
                                        <span class="menu-text"> ESPECIALIDADES </span>
                                    </a>
                                </li>
                                <li id="reportes-1">
                                    <a href="#" class="dropdown-toggle">
                                        <i class="icon-print"></i>
                                        <span class="menu-text"> REPORTES </span>
                                        <b class="arrow icon-angle-down"></b>
                                    </a>
                                    <ul class="submenu">
                                        <li>
                                            <a href="<?php echo $this->url('eventos') ?>">
                                                <i class="icon-list bigger-120"></i>
                                                <span class="menu-text"> EVENTOS </span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('zfcuser/logout') ?>">
                                        <i class="icon-signout bigger-120"></i>
                                        <span class="menu-text"> SALIR </span>
                                    </a>
                                </li>
                            </ul><!--/.nav-list-->

                            <div class="sidebar-collapse" id="sidebar-collapse">
                                <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
                            </div>

                            <script >
                                try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
                            </script>
                        </div>
                        

                        <!-- Aqui va incluido el contenido de la pagina -->
                        <?php echo $this->content; ?>
                        <!-- Aqui termina el contenido de la pagina-->
                        
                        
                        <div class="ace-settings-container" id="ace-settings-container">
                            <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
                                <i class="icon-cog bigger-150"></i>
                            </div>
                            <div class="ace-settings-box" id="ace-settings-box">
                                <div>
                                    <div class="pull-left">
                                        <select id="skin-colorpicker" class="hide">
                                            <option data-skin="default" value="#438EB9">#438EB9</option>
                                            <option data-skin="skin-1" value="#222A2D">#222A2D</option>
                                            <option data-skin="skin-2" value="#C6487E">#C6487E</option>
                                            <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
                                        </select>
                                    </div>
                                    <span>&nbsp; Choose Skin</span>
                                </div>
                                <div>
                                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar" />
                                    <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
                                </div>
                                <div>
                                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar" />
                                    <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
                                </div>
                                <div>
                                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs" />
                                    <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
                                </div>
                                <div>
                                    <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl" />
                                    <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
                                </div>
                                <div>
                                    <input  type="checkbox" class="ace ace-checkbox-2" id="ace-settings-add-container" checked='checked'/>
                                    <label class="lbl" for="ace-settings-add-container">
                                            Inside
                                            <b>.container</b>
                                    </label>
                                </div>
                            </div>
                        </div><!-- /#ace-settings-container -->
                    </div><!-- /.main-container-inner -->
                    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
                        <i class="icon-double-angle-up icon-only bigger-110"></i>
                    </a>
		</div><!--/.main-container-->
                <script>
                    $("#m_1").click(function(){
                        window.open('manuales/programador.pdf','_blank');
                    });
                    $("#m_2").click(function(){
                        window.open('manuales/analista.pdf','_blank');
                    });
                    $("#m_3").click(function(){
                        window.open('manuales/diseno.pdf','_blank');
                    });
                    $("#m_4").click(function(){
                        window.open('manuales/operador.pdf','_blank');
                    });
                </script>
	</body>
</html>